/* Automatically generated by tree-sitter v0.25.1 (f5afe475deb7c0bae6407fb776c76824f717bb61) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 66
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_module = 1,
  anon_sym_SEMI = 2,
  anon_sym_import = 3,
  anon_sym_as = 4,
  anon_sym_export = 5,
  anon_sym_Float16 = 6,
  anon_sym_Float32 = 7,
  anon_sym_Float64 = 8,
  anon_sym_Bool = 9,
  anon_sym_String = 10,
  sym_Integer_type = 11,
  anon_sym_struct = 12,
  anon_sym_LBRACE = 13,
  anon_sym_RBRACE = 14,
  anon_sym_COLON = 15,
  anon_sym_EQ = 16,
  anon_sym_LBRACE_RBRACE = 17,
  sym_Identifier = 18,
  anon_sym_DOT = 19,
  anon_sym_true = 20,
  anon_sym_false = 21,
  sym_Number = 22,
  sym_String = 23,
  sym_Comment = 24,
  sym_Module = 25,
  sym_Module_head = 26,
  sym_Module_declaration = 27,
  sym_Module_name = 28,
  sym_Import = 29,
  sym_Import_name = 30,
  sym_Import_alias = 31,
  sym_Declaration = 32,
  sym_Type = 33,
  sym_Type_name = 34,
  sym_Builtin_type = 35,
  sym_Struct = 36,
  sym_Struct_name = 37,
  sym_Struct_member = 38,
  sym_Struct_member_name = 39,
  sym_Struct_member_type = 40,
  sym_Generic_expression_or_instantiate = 41,
  sym_Generic_expression = 42,
  sym_Expression_constant = 43,
  sym_Expression_instantiate = 44,
  sym_Identifier_with_dots = 45,
  sym_Boolean = 46,
  aux_sym_Module_repeat1 = 47,
  aux_sym_Module_head_repeat1 = 48,
  aux_sym_Struct_repeat1 = 49,
  aux_sym_Identifier_with_dots_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_module] = "module",
  [anon_sym_SEMI] = ";",
  [anon_sym_import] = "import",
  [anon_sym_as] = "as",
  [anon_sym_export] = "export",
  [anon_sym_Float16] = "Float16",
  [anon_sym_Float32] = "Float32",
  [anon_sym_Float64] = "Float64",
  [anon_sym_Bool] = "Bool",
  [anon_sym_String] = "String",
  [sym_Integer_type] = "Integer_type",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE_RBRACE] = "{}",
  [sym_Identifier] = "Identifier",
  [anon_sym_DOT] = ".",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_Number] = "Number",
  [sym_String] = "String",
  [sym_Comment] = "Comment",
  [sym_Module] = "Module",
  [sym_Module_head] = "Module_head",
  [sym_Module_declaration] = "Module_declaration",
  [sym_Module_name] = "Module_name",
  [sym_Import] = "Import",
  [sym_Import_name] = "Import_name",
  [sym_Import_alias] = "Import_alias",
  [sym_Declaration] = "Declaration",
  [sym_Type] = "Type",
  [sym_Type_name] = "Type_name",
  [sym_Builtin_type] = "Builtin_type",
  [sym_Struct] = "Struct",
  [sym_Struct_name] = "Struct_name",
  [sym_Struct_member] = "Struct_member",
  [sym_Struct_member_name] = "Struct_member_name",
  [sym_Struct_member_type] = "Struct_member_type",
  [sym_Generic_expression_or_instantiate] = "Generic_expression_or_instantiate",
  [sym_Generic_expression] = "Generic_expression",
  [sym_Expression_constant] = "Expression_constant",
  [sym_Expression_instantiate] = "Expression_instantiate",
  [sym_Identifier_with_dots] = "Identifier_with_dots",
  [sym_Boolean] = "Boolean",
  [aux_sym_Module_repeat1] = "Module_repeat1",
  [aux_sym_Module_head_repeat1] = "Module_head_repeat1",
  [aux_sym_Struct_repeat1] = "Struct_repeat1",
  [aux_sym_Identifier_with_dots_repeat1] = "Identifier_with_dots_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_Float16] = anon_sym_Float16,
  [anon_sym_Float32] = anon_sym_Float32,
  [anon_sym_Float64] = anon_sym_Float64,
  [anon_sym_Bool] = anon_sym_Bool,
  [anon_sym_String] = anon_sym_String,
  [sym_Integer_type] = sym_Integer_type,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE_RBRACE] = anon_sym_LBRACE_RBRACE,
  [sym_Identifier] = sym_Identifier,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_Number] = sym_Number,
  [sym_String] = sym_String,
  [sym_Comment] = sym_Comment,
  [sym_Module] = sym_Module,
  [sym_Module_head] = sym_Module_head,
  [sym_Module_declaration] = sym_Module_declaration,
  [sym_Module_name] = sym_Module_name,
  [sym_Import] = sym_Import,
  [sym_Import_name] = sym_Import_name,
  [sym_Import_alias] = sym_Import_alias,
  [sym_Declaration] = sym_Declaration,
  [sym_Type] = sym_Type,
  [sym_Type_name] = sym_Type_name,
  [sym_Builtin_type] = sym_Builtin_type,
  [sym_Struct] = sym_Struct,
  [sym_Struct_name] = sym_Struct_name,
  [sym_Struct_member] = sym_Struct_member,
  [sym_Struct_member_name] = sym_Struct_member_name,
  [sym_Struct_member_type] = sym_Struct_member_type,
  [sym_Generic_expression_or_instantiate] = sym_Generic_expression_or_instantiate,
  [sym_Generic_expression] = sym_Generic_expression,
  [sym_Expression_constant] = sym_Expression_constant,
  [sym_Expression_instantiate] = sym_Expression_instantiate,
  [sym_Identifier_with_dots] = sym_Identifier_with_dots,
  [sym_Boolean] = sym_Boolean,
  [aux_sym_Module_repeat1] = aux_sym_Module_repeat1,
  [aux_sym_Module_head_repeat1] = aux_sym_Module_head_repeat1,
  [aux_sym_Struct_repeat1] = aux_sym_Struct_repeat1,
  [aux_sym_Identifier_with_dots_repeat1] = aux_sym_Identifier_with_dots_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Float16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Float32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Float64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [sym_Integer_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_Identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_Number] = {
    .visible = true,
    .named = true,
  },
  [sym_String] = {
    .visible = true,
    .named = true,
  },
  [sym_Comment] = {
    .visible = true,
    .named = true,
  },
  [sym_Module] = {
    .visible = true,
    .named = true,
  },
  [sym_Module_head] = {
    .visible = true,
    .named = true,
  },
  [sym_Module_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_Module_name] = {
    .visible = true,
    .named = true,
  },
  [sym_Import] = {
    .visible = true,
    .named = true,
  },
  [sym_Import_name] = {
    .visible = true,
    .named = true,
  },
  [sym_Import_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_Declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_Type] = {
    .visible = true,
    .named = true,
  },
  [sym_Type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_Builtin_type] = {
    .visible = true,
    .named = true,
  },
  [sym_Struct] = {
    .visible = true,
    .named = true,
  },
  [sym_Struct_name] = {
    .visible = true,
    .named = true,
  },
  [sym_Struct_member] = {
    .visible = true,
    .named = true,
  },
  [sym_Struct_member_name] = {
    .visible = true,
    .named = true,
  },
  [sym_Struct_member_type] = {
    .visible = true,
    .named = true,
  },
  [sym_Generic_expression_or_instantiate] = {
    .visible = true,
    .named = true,
  },
  [sym_Generic_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_Expression_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_Expression_instantiate] = {
    .visible = true,
    .named = true,
  },
  [sym_Identifier_with_dots] = {
    .visible = true,
    .named = true,
  },
  [sym_Boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_Module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_Module_head_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_Struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_Identifier_with_dots_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(55);
      ADVANCE_MAP(
        '"', 2,
        '.', 95,
        '/', 4,
        ':', 74,
        ';', 57,
        '=', 75,
        'B', 30,
        'F', 24,
        'I', 27,
        'S', 48,
        'U', 19,
        'a', 41,
        'e', 53,
        'f', 11,
        'i', 25,
        'm', 28,
        's', 49,
        't', 36,
        '{', 72,
        '}', 73,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(11);
      if (lookahead == 't') ADVANCE(36);
      if (lookahead == '{') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '}') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(100);
      END_STATE();
    case 5:
      if (lookahead == '1') ADVANCE(9);
      if (lookahead == '3') ADVANCE(6);
      if (lookahead == '6') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == '2') ADVANCE(62);
      END_STATE();
    case 7:
      if (lookahead == '4') ADVANCE(63);
      END_STATE();
    case 8:
      if (lookahead == '6') ADVANCE(69);
      if (('7' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (('1' <= lookahead && lookahead <= '5')) ADVANCE(70);
      END_STATE();
    case 9:
      if (lookahead == '6') ADVANCE(61);
      END_STATE();
    case 10:
      if (lookahead == 'B') ADVANCE(88);
      if (lookahead == 'F') ADVANCE(84);
      if (lookahead == 'I') ADVANCE(86);
      if (lookahead == 'S') ADVANCE(91);
      if (lookahead == 'U') ADVANCE(81);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(52);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 18:
      if (lookahead == 'g') ADVANCE(66);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(64);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 25:
      if (lookahead == 'm') ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 32:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 33:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 34:
      if (lookahead == 'p') ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == 'p') ADVANCE(33);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(59);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(5);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(71);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 50:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 51:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 53:
      if (lookahead == 'x') ADVANCE(34);
      END_STATE();
    case 54:
      if (lookahead == '}') ADVANCE(76);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_Float16);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_Float32);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_Float64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_Bool);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_Bool);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_String);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_Integer_type);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_Integer_type);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_Integer_type);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LBRACE_RBRACE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == '1') ADVANCE(9);
      if (lookahead == '3') ADVANCE(6);
      if (lookahead == '6') ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == '6') ADVANCE(69);
      if (('7' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (('1' <= lookahead && lookahead <= '5')) ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 'a') ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 'g') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 'i') ADVANCE(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 'i') ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 'l') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 'l') ADVANCE(87);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 'n') ADVANCE(80);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 'n') ADVANCE(92);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 'o') ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 'o') ADVANCE(89);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 'o') ADVANCE(83);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 'r') ADVANCE(82);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 't') ADVANCE(90);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 't') ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_Identifier);
      if (lookahead == 't') ADVANCE(77);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_Identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_Number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_String);
      if (lookahead == '"') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_Comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 10},
  [3] = {.lex_state = 10},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_Float16] = ACTIONS(1),
    [anon_sym_Float32] = ACTIONS(1),
    [anon_sym_Float64] = ACTIONS(1),
    [anon_sym_Bool] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [sym_Integer_type] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_Number] = ACTIONS(1),
    [sym_String] = ACTIONS(1),
    [sym_Comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_Module] = STATE(39),
    [sym_Module_head] = STATE(7),
    [sym_Module_declaration] = STATE(6),
    [anon_sym_module] = ACTIONS(3),
    [sym_Comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(11), 1,
      sym_Identifier,
    STATE(51), 1,
      sym_Type,
    STATE(53), 1,
      sym_Struct_member_type,
    ACTIONS(9), 2,
      anon_sym_Bool,
      anon_sym_String,
    STATE(52), 2,
      sym_Type_name,
      sym_Builtin_type,
    ACTIONS(7), 4,
      anon_sym_Float16,
      anon_sym_Float32,
      anon_sym_Float64,
      sym_Integer_type,
  [24] = 6,
    ACTIONS(11), 1,
      sym_Identifier,
    STATE(38), 1,
      sym_Struct_member_type,
    STATE(51), 1,
      sym_Type,
    ACTIONS(9), 2,
      anon_sym_Bool,
      anon_sym_String,
    STATE(52), 2,
      sym_Type_name,
      sym_Builtin_type,
    ACTIONS(7), 4,
      anon_sym_Float16,
      anon_sym_Float32,
      anon_sym_Float64,
      sym_Integer_type,
  [48] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(59), 1,
      sym_Boolean,
    STATE(62), 1,
      sym_Expression_constant,
    STATE(63), 1,
      sym_Generic_expression_or_instantiate,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 2,
      sym_Number,
      sym_String,
    STATE(61), 2,
      sym_Generic_expression,
      sym_Expression_instantiate,
  [73] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(59), 1,
      sym_Boolean,
    STATE(60), 1,
      sym_Generic_expression_or_instantiate,
    STATE(62), 1,
      sym_Expression_constant,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 2,
      sym_Number,
      sym_String,
    STATE(61), 2,
      sym_Generic_expression,
      sym_Expression_instantiate,
  [98] = 3,
    ACTIONS(21), 1,
      anon_sym_import,
    STATE(9), 2,
      sym_Import,
      aux_sym_Module_head_repeat1,
    ACTIONS(19), 4,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_struct,
      sym_Comment,
  [112] = 6,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_export,
    ACTIONS(27), 1,
      anon_sym_struct,
    ACTIONS(29), 1,
      sym_Comment,
    STATE(24), 1,
      sym_Struct,
    STATE(8), 2,
      sym_Declaration,
      aux_sym_Module_repeat1,
  [132] = 6,
    ACTIONS(25), 1,
      anon_sym_export,
    ACTIONS(27), 1,
      anon_sym_struct,
    ACTIONS(29), 1,
      sym_Comment,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      sym_Struct,
    STATE(11), 2,
      sym_Declaration,
      aux_sym_Module_repeat1,
  [152] = 3,
    ACTIONS(21), 1,
      anon_sym_import,
    STATE(10), 2,
      sym_Import,
      aux_sym_Module_head_repeat1,
    ACTIONS(33), 4,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_struct,
      sym_Comment,
  [166] = 3,
    ACTIONS(37), 1,
      anon_sym_import,
    STATE(10), 2,
      sym_Import,
      aux_sym_Module_head_repeat1,
    ACTIONS(35), 4,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_struct,
      sym_Comment,
  [180] = 6,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      anon_sym_export,
    ACTIONS(45), 1,
      anon_sym_struct,
    ACTIONS(48), 1,
      sym_Comment,
    STATE(24), 1,
      sym_Struct,
    STATE(11), 2,
      sym_Declaration,
      aux_sym_Module_repeat1,
  [200] = 5,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 1,
      sym_Identifier,
    ACTIONS(56), 1,
      sym_Comment,
    STATE(65), 1,
      sym_Struct_member_name,
    STATE(12), 2,
      sym_Struct_member,
      aux_sym_Struct_repeat1,
  [217] = 5,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    ACTIONS(61), 1,
      sym_Identifier,
    ACTIONS(63), 1,
      sym_Comment,
    STATE(65), 1,
      sym_Struct_member_name,
    STATE(12), 2,
      sym_Struct_member,
      aux_sym_Struct_repeat1,
  [234] = 5,
    ACTIONS(61), 1,
      sym_Identifier,
    ACTIONS(63), 1,
      sym_Comment,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      sym_Struct_member_name,
    STATE(13), 2,
      sym_Struct_member,
      aux_sym_Struct_repeat1,
  [251] = 1,
    ACTIONS(67), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      sym_Comment,
  [259] = 1,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      sym_Comment,
  [267] = 1,
    ACTIONS(71), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      sym_Comment,
  [275] = 3,
    ACTIONS(75), 1,
      anon_sym_DOT,
    STATE(23), 1,
      aux_sym_Identifier_with_dots_repeat1,
    ACTIONS(73), 2,
      anon_sym_SEMI,
      anon_sym_as,
  [286] = 1,
    ACTIONS(77), 4,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_struct,
      sym_Comment,
  [293] = 1,
    ACTIONS(79), 4,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_struct,
      sym_Comment,
  [300] = 3,
    ACTIONS(83), 1,
      anon_sym_DOT,
    STATE(21), 1,
      aux_sym_Identifier_with_dots_repeat1,
    ACTIONS(81), 2,
      anon_sym_SEMI,
      anon_sym_as,
  [311] = 1,
    ACTIONS(86), 4,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_struct,
      sym_Comment,
  [318] = 3,
    ACTIONS(75), 1,
      anon_sym_DOT,
    STATE(21), 1,
      aux_sym_Identifier_with_dots_repeat1,
    ACTIONS(88), 2,
      anon_sym_SEMI,
      anon_sym_as,
  [329] = 1,
    ACTIONS(90), 4,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_struct,
      sym_Comment,
  [336] = 1,
    ACTIONS(92), 4,
      ts_builtin_sym_end,
      anon_sym_export,
      anon_sym_struct,
      sym_Comment,
  [343] = 1,
    ACTIONS(81), 3,
      anon_sym_SEMI,
      anon_sym_as,
      anon_sym_DOT,
  [349] = 3,
    ACTIONS(94), 1,
      sym_Identifier,
    STATE(44), 1,
      sym_Module_name,
    STATE(48), 1,
      sym_Identifier_with_dots,
  [359] = 1,
    ACTIONS(96), 3,
      anon_sym_RBRACE,
      sym_Identifier,
      sym_Comment,
  [365] = 3,
    ACTIONS(94), 1,
      sym_Identifier,
    STATE(46), 1,
      sym_Import_name,
    STATE(47), 1,
      sym_Identifier_with_dots,
  [375] = 3,
    ACTIONS(94), 1,
      sym_Identifier,
    STATE(45), 1,
      sym_Module_name,
    STATE(48), 1,
      sym_Identifier_with_dots,
  [385] = 3,
    ACTIONS(27), 1,
      anon_sym_struct,
    ACTIONS(98), 1,
      anon_sym_export,
    STATE(20), 1,
      sym_Struct,
  [395] = 1,
    ACTIONS(100), 3,
      anon_sym_RBRACE,
      sym_Identifier,
      sym_Comment,
  [401] = 2,
    ACTIONS(27), 1,
      anon_sym_struct,
    STATE(20), 1,
      sym_Struct,
  [408] = 2,
    ACTIONS(27), 1,
      anon_sym_struct,
    STATE(19), 1,
      sym_Struct,
  [415] = 2,
    ACTIONS(102), 1,
      sym_Identifier,
    STATE(42), 1,
      sym_Import_alias,
  [422] = 2,
    ACTIONS(104), 1,
      sym_Identifier,
    STATE(40), 1,
      sym_Struct_name,
  [429] = 2,
    ACTIONS(61), 1,
      sym_Identifier,
    STATE(43), 1,
      sym_Struct_member_name,
  [436] = 1,
    ACTIONS(106), 1,
      anon_sym_EQ,
  [440] = 1,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
  [444] = 1,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
  [448] = 1,
    ACTIONS(112), 1,
      anon_sym_SEMI,
  [452] = 1,
    ACTIONS(114), 1,
      anon_sym_SEMI,
  [456] = 1,
    ACTIONS(116), 1,
      anon_sym_COLON,
  [460] = 1,
    ACTIONS(118), 1,
      anon_sym_SEMI,
  [464] = 1,
    ACTIONS(120), 1,
      anon_sym_SEMI,
  [468] = 1,
    ACTIONS(122), 1,
      anon_sym_as,
  [472] = 1,
    ACTIONS(124), 1,
      anon_sym_as,
  [476] = 1,
    ACTIONS(126), 1,
      anon_sym_SEMI,
  [480] = 1,
    ACTIONS(128), 1,
      anon_sym_EQ,
  [484] = 1,
    ACTIONS(130), 1,
      anon_sym_EQ,
  [488] = 1,
    ACTIONS(132), 1,
      anon_sym_EQ,
  [492] = 1,
    ACTIONS(134), 1,
      anon_sym_EQ,
  [496] = 1,
    ACTIONS(136), 1,
      anon_sym_EQ,
  [500] = 1,
    ACTIONS(138), 1,
      anon_sym_COLON,
  [504] = 1,
    ACTIONS(140), 1,
      anon_sym_module,
  [508] = 1,
    ACTIONS(142), 1,
      sym_Identifier,
  [512] = 1,
    ACTIONS(144), 1,
      anon_sym_SEMI,
  [516] = 1,
    ACTIONS(146), 1,
      anon_sym_SEMI,
  [520] = 1,
    ACTIONS(148), 1,
      anon_sym_SEMI,
  [524] = 1,
    ACTIONS(150), 1,
      anon_sym_SEMI,
  [528] = 1,
    ACTIONS(152), 1,
      anon_sym_SEMI,
  [532] = 1,
    ACTIONS(154), 1,
      anon_sym_SEMI,
  [536] = 1,
    ACTIONS(156), 1,
      anon_sym_SEMI,
  [540] = 1,
    ACTIONS(158), 1,
      anon_sym_LBRACE,
  [544] = 1,
    ACTIONS(160), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 73,
  [SMALL_STATE(6)] = 98,
  [SMALL_STATE(7)] = 112,
  [SMALL_STATE(8)] = 132,
  [SMALL_STATE(9)] = 152,
  [SMALL_STATE(10)] = 166,
  [SMALL_STATE(11)] = 180,
  [SMALL_STATE(12)] = 200,
  [SMALL_STATE(13)] = 217,
  [SMALL_STATE(14)] = 234,
  [SMALL_STATE(15)] = 251,
  [SMALL_STATE(16)] = 259,
  [SMALL_STATE(17)] = 267,
  [SMALL_STATE(18)] = 275,
  [SMALL_STATE(19)] = 286,
  [SMALL_STATE(20)] = 293,
  [SMALL_STATE(21)] = 300,
  [SMALL_STATE(22)] = 311,
  [SMALL_STATE(23)] = 318,
  [SMALL_STATE(24)] = 329,
  [SMALL_STATE(25)] = 336,
  [SMALL_STATE(26)] = 343,
  [SMALL_STATE(27)] = 349,
  [SMALL_STATE(28)] = 359,
  [SMALL_STATE(29)] = 365,
  [SMALL_STATE(30)] = 375,
  [SMALL_STATE(31)] = 385,
  [SMALL_STATE(32)] = 395,
  [SMALL_STATE(33)] = 401,
  [SMALL_STATE(34)] = 408,
  [SMALL_STATE(35)] = 415,
  [SMALL_STATE(36)] = 422,
  [SMALL_STATE(37)] = 429,
  [SMALL_STATE(38)] = 436,
  [SMALL_STATE(39)] = 440,
  [SMALL_STATE(40)] = 444,
  [SMALL_STATE(41)] = 448,
  [SMALL_STATE(42)] = 452,
  [SMALL_STATE(43)] = 456,
  [SMALL_STATE(44)] = 460,
  [SMALL_STATE(45)] = 464,
  [SMALL_STATE(46)] = 468,
  [SMALL_STATE(47)] = 472,
  [SMALL_STATE(48)] = 476,
  [SMALL_STATE(49)] = 480,
  [SMALL_STATE(50)] = 484,
  [SMALL_STATE(51)] = 488,
  [SMALL_STATE(52)] = 492,
  [SMALL_STATE(53)] = 496,
  [SMALL_STATE(54)] = 500,
  [SMALL_STATE(55)] = 504,
  [SMALL_STATE(56)] = 508,
  [SMALL_STATE(57)] = 512,
  [SMALL_STATE(58)] = 516,
  [SMALL_STATE(59)] = 520,
  [SMALL_STATE(60)] = 524,
  [SMALL_STATE(61)] = 528,
  [SMALL_STATE(62)] = 532,
  [SMALL_STATE(63)] = 536,
  [SMALL_STATE(64)] = 540,
  [SMALL_STATE(65)] = 544,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Module_head, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Module, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Module, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Module_head, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_Module_head_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Module_head_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_Module_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Module_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Module_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Module_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_Struct_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Struct_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Struct_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Module_declaration, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Import, 5, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Module_declaration, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Identifier_with_dots, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Declaration, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Declaration, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_Identifier_with_dots_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Identifier_with_dots_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Struct, 4, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Identifier_with_dots, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Declaration, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Struct, 5, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Struct_member, 7, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Struct_member, 6, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [108] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Import_alias, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Import_name, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Module_name, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Builtin_type, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Type_name, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Struct_member_type, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Type, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Struct_member_name, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Expression_instantiate, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Boolean, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Expression_constant, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Generic_expression_or_instantiate, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Generic_expression, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Struct_name, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hlang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hlang",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
